{{- $createSecret := false -}}
{{- if not .Values.postgres.existingSecret }}{{ $createSecret = true }}{{ end -}}
{{- if and .Values.redis.auth.enabled (not .Values.redis.existingSecret) }}{{ $createSecret = true }}{{ end -}}
{{- if not .Values.s3.existingSecret }}{{ $createSecret = true }}{{ end -}}
{{- if and .Values.oauth.github.enabled (not .Values.oauth.github.existingSecret) }}{{ $createSecret = true }}{{ end -}}

{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cargohold.fullname" . }}
  labels:
    {{ include "cargohold.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.postgres.existingSecret }}
  database-password: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.auth.enabled (not .Values.redis.existingSecret) }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.s3.existingSecret }}
  s3-access-key-id: {{ .Values.s3.credentials.accessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ .Values.s3.credentials.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oauth.github.enabled (not .Values.oauth.github.existingSecret) }}
  github-oauth-client-id: {{ .Values.oauth.github.clientId | default "" | b64enc | quote }}
  github-oauth-client-secret: {{ .Values.oauth.github.clientSecret | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
